name: BUILD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Pnpm setup
        uses: pnpm/action-setup@v4

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: dependency-cache-${{ hashFiles('package.json') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check types
        run: pnpm tsc

      - name: Lint project
        run: pnpm lint

      - name: Format project
        run: pnpm format

      - name: Build packages
        run: pnpm build
