name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update NPM version
        run: npm install -g npm@9

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: dependency-cache-${{ hashFiles('package.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build
